# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  verify:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/openjdk:11.0-node

    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout

      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}

      - run:
          name: "build project"
          command: |
            mvn clean install

      - run:
          name: "prepare aio"
          command: |
            npm install -g @adobe/aio-cli
            aio plugins:install @adobe/aio-cli-plugin-cloudmanager
            aio plugins:install @adobe/aio-cli-plugin-aem-rde
            aio plugins:update

      - run:
          name: "aio login"
          command: |
            echo "${SERVICE_ACCOUNT_PRIVATE_KEY_B64}" | base64 -d > private.key
            
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.client_id "${SERVICE_ACCOUNT_CLIENT_ID}"
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.client_secret "${SERVICE_ACCOUNT_CLIENT_SECRET}"
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.technical_account_id "${SERVICE_ACCOUNT_TECH_ACCOUNT_ID}"
            aio config:set  --json ims.contexts.aio-cli-plugin-cloudmanager.meta_scopes '["ent_cloudmgr_sdk"]'
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.ims_org_id "${SERVICE_ACCOUNT_ORG_ID}"
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.private_key  private.key --file
            
            aio auth login --ctx=aio-cli-plugin-cloudmanager > login.log
            
      - run:
          name: "Configure the RDE coordinates"
          command: |
            aio config:set cloudmanager_orgid  "${SERVICE_ACCOUNT_ORG_ID}"
            aio config:set cloudmanager_programid "${PROGRAM_ID}" 
            aio config:set cloudmanager_environmentid "${ENVIRONMENT_ID}"

      - run:
          name: "reset the RDE"
          no_output_timeout: 15m
          command: |
                time aio aem:rde:reset

      - run:
          name: "setup new admin user on RDE"
          command: |
            # Note: I have observed some install failures if the user/password contain special characters like "+"
            # this is currently being investigated: SKYOPS-52856
            .circleci/create-user-osgi-cfg.sh -u "${AEM_USER}" -p "${AEM_PASSWORD}" -q true
            
            aio aem:rde:install -t osgi-config org.apache.sling.jcr.repoinit.RepositoryInitializer~testadmin-user-add.cfg.json
            
            # delete the osgi config, this is fine since the script contained within the config is not reverterd
            aio aem:rde:delete org.apache.sling.jcr.repoinit.RepositoryInitializer~testadmin-user-add

      - run:
          name: "install project on RDE"
          command: |
            ALL_FILE=$(ls all/target/ | grep zip ) && aio aem:rde:install -t content-package "all/target/${ALL_FILE}"
            DISP_FILE=$(ls dispatcher/target/ | grep zip ) && aio aem:rde:install -t dispatcher-config "dispatcher/target/${DISP_FILE}"

            # todo: we can check the status of the installation with "aio aem:rde:status"
            echo "waiting 20s to finish rde install"
            sleep 20

      - run:
          name: "Run Local Integration Tests"
          command: |
            cd it.tests 
            mvn clean verify \
            -Plocal \
            -Dit.author.url="${AUTHOR_URL}" \
            -Dit.author.user="${AEM_USER}" \
            -Dit.author.password="${AEM_PASSWORD}" \
            -Dit.publish.url="${PUBLISH_URL}" \
            -Dit.publish.user="${AEM_USER}" \
            -Dit.publish.password="${AEM_PASSWORD}" \
            -Dmaven.javadoc.skip=true \
            -Dmaven.surefire.debug

      - save_cache:
          key: maven-{{ checksum "pom.xml" }}
          paths:
            - /home/circleci/.m2/repository/

      - run:
          name: "download Eaas cli"
          command: |
            curl -L https://github.com/andresbott/aem-guides-wknd/releases/download/poc-eaas/eaas-0.4.4  --output eaas
            chmod +x ./eaas
            sudo mv ./eaas /usr/local/bin/eaas

      - run:
          name: "Eaas login"
          command: |
            echo "${SERVICE_ACCOUNT_PRIVATE_KEY_B64}" | base64 -d > private.key
            eaas --url="https://devxapi.adobe.io" login integration  \
              --organization "${SERVICE_ACCOUNT_ORG_ID}" \
              --clientId "${SERVICE_ACCOUNT_CLIENT_ID}" \
              --secret "${SERVICE_ACCOUNT_CLIENT_SECRET}" \
              --privateKey private.key \
              --accountId "${SERVICE_ACCOUNT_TECH_ACCOUNT_ID}"            
            eaas health
      - run:
          name: "Generate the IT payload"
          command: |
            eaas generate it-task-payload
            
            sed -i "s|groupId:test-module-artifactId:version|com.adobe.cq.cloud:com.adobe.cq.cloud.testing.it.smoke:0.14.8-4f7653d|g ;
            s|https:\/\/author-skyline:port|${AUTHOR_URL}|g ;
            s|https:\/\/publish-skyline:port|${PUBLISH_URL}|g ;
            s/authorPV\\$\\$/${AEM_PASSWORD}/g ;
            s/publishPV\\$\\$/${AEM_PASSWORD}/g ;
            s/user\":\ \"admin/user\": \"${AEM_USER}/g ;
            " it-task-payload.json            

      - run:
          name: "Run the IT task"
          command: |
            # Start the IT Task            
            eaas start it-task -f it-task-payload.json | tee it-task.out
            task_id="`cat it-task.out | grep "Id:" | awk -F':' '{print $2}' | xargs`"
            if [[ "${task_id}" == "" ]]; then
                echo "EAAS failed to generate task_id"
                exit 1
            fi
            
            # Check IT Task status
            start_time="`date +%s`"
            IT_TASK_TIMEOUT=900
            status_file="taskId-${task_id}.status"
            while true; do
              eaas status it-task --taskId ${task_id} | tee "${status_file}"
              test_status="`cat "${status_file}" | grep "Status:" | awk -F':' '{print $2}' | xargs `"
              if [[ "${test_status}" == "terminated" || "${test_status}" == "failed" || $((`date +%s` - ${start_time})) -gt ${IT_TASK_TIMEOUT} ]]; then
                break
              fi
            echo "waiting 10s to check again for task status"
            sleep 10
            done
            
            # parse results
            test_passed="`cat "${status_file}" | grep "Tests passed:" | awk -F':' '{print $2}' | xargs `"
            echo ${task_id}
            echo ${test_status} 
            echo ${test_passed} 
            
            # Generate task exit code
            if [[ "${test_passed}" == "true" ]]; then exit 0; else exit 1; fi           
            

      - run:
          name: Uninstall the user from the RDE
          command: |
            aio aem:rde:install -t osgi-config org.apache.sling.jcr.repoinit.RepositoryInitializer~testadmin-user-remove.cfg.json
            aio aem:rde:delete org.apache.sling.jcr.repoinit.RepositoryInitializer~testadmin-user-remove
          when: always

  Build:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}

      - run:
          name: "build project"
          command: |
            mkdir -p workspace/all
            mkdir -p workspace/dispatcher
            mvn clean install

      - run:
          name: "copy build artifacts"
          command: |
            cp -r all/target/*.zip workspace/all
            cp -r dispatcher/target/*.zip workspace/dispatcher

      - persist_to_workspace:
          root: workspace
          paths:
            - all
            - dispatcher

      - save_cache:
          key: maven-{{ checksum "pom.xml" }}
          paths:
            - /home/circleci/.m2/repository/


  RDE-reset:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - run:
          name: "Install aio-cli"
          command: |
            npm install -g @adobe/aio-cli
            aio plugins:install @adobe/aio-cli-plugin-cloudmanager
            aio plugins:install @adobe/aio-cli-plugin-aem-rde
            aio plugins:update

      - run:
          name: "aio login"
          command: |
            echo "${SERVICE_ACCOUNT_PRIVATE_KEY_B64}" | base64 -d > private.key
            
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.client_id "${SERVICE_ACCOUNT_CLIENT_ID}"
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.client_secret "${SERVICE_ACCOUNT_CLIENT_SECRET}"
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.technical_account_id "${SERVICE_ACCOUNT_TECH_ACCOUNT_ID}"
            aio config:set  --json ims.contexts.aio-cli-plugin-cloudmanager.meta_scopes '["ent_cloudmgr_sdk"]'
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.ims_org_id "${SERVICE_ACCOUNT_ORG_ID}"
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.private_key  private.key --file
            
            aio auth login --ctx=aio-cli-plugin-cloudmanager > login.log
            
            # configure coordinates
            aio config:set cloudmanager_orgid  "${SERVICE_ACCOUNT_ORG_ID}"
            aio config:set cloudmanager_programid "${PROGRAM_ID}" 
            aio config:set cloudmanager_environmentid "${ENVIRONMENT_ID}"

      - run:
          name: "reset the RDE"
          no_output_timeout: 15m
          command: |
            time aio aem:rde:reset

  RDE-install:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - checkout
      - run:
          name: "Install aio-cli"
          command: |
            npm install -g @adobe/aio-cli
            aio plugins:install @adobe/aio-cli-plugin-cloudmanager
            aio plugins:install @adobe/aio-cli-plugin-aem-rde
            aio plugins:update
      - run:
          name: "aio login"
          command: |
            echo "${SERVICE_ACCOUNT_PRIVATE_KEY_B64}" | base64 -d > private.key
            
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.client_id "${SERVICE_ACCOUNT_CLIENT_ID}"
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.client_secret "${SERVICE_ACCOUNT_CLIENT_SECRET}"
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.technical_account_id "${SERVICE_ACCOUNT_TECH_ACCOUNT_ID}"
            aio config:set  --json ims.contexts.aio-cli-plugin-cloudmanager.meta_scopes '["ent_cloudmgr_sdk"]'
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.ims_org_id "${SERVICE_ACCOUNT_ORG_ID}"
            aio config:set ims.contexts.aio-cli-plugin-cloudmanager.private_key  private.key --file
            
            aio auth login --ctx=aio-cli-plugin-cloudmanager > login.log
            
            # configure coordinates
            aio config:set cloudmanager_orgid  "${SERVICE_ACCOUNT_ORG_ID}"
            aio config:set cloudmanager_programid "${PROGRAM_ID}" 
            aio config:set cloudmanager_environmentid "${ENVIRONMENT_ID}"

      - run:
          name: "setup new admin user on RDE"
          command: |
            # Note: repoinit has some limitations with special characters in password, e.g. "+" sign
            .circleci/create-user-osgi-cfg.sh -u "${AEM_USER}" -p "${AEM_PASSWORD}" -q true
            
            aio aem:rde:install -t osgi-config org.apache.sling.jcr.repoinit.RepositoryInitializer~testadmin-user-add.cfg.json
            
            # delete the osgi config, this is fine since the script contained within the config is not reverterd
            aio aem:rde:delete org.apache.sling.jcr.repoinit.RepositoryInitializer~testadmin-user-add    

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: "install project on RDE"
          command: |
            set -e
            ALL_FILE=$(ls /tmp/workspace/all/ | grep zip ) && aio aem:rde:install -t content-package "/tmp/workspace/all/${ALL_FILE}"
            DISP_FILE=$(ls /tmp/workspace/dispatcher/ | grep zip ) && aio aem:rde:install -t dispatcher-config "/tmp/workspace/dispatcher/${DISP_FILE}"

            # todo: we can check the status of the installation with "aio aem:rde:status"
            echo "waiting 20s to finish rde install"
            sleep 20    
            

  Customer-ITs:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
      - run:
          name: "Run Local Integration Tests"
          command: |
            cd it.tests 
            mvn clean verify \
            -Plocal \
            -Dit.author.url="${AUTHOR_URL}" \
            -Dit.author.user="${AEM_USER}" \
            -Dit.author.password="${AEM_PASSWORD}" \
            -Dit.publish.url="${PUBLISH_URL}" \
            -Dit.publish.user="${AEM_USER}" \
            -Dit.publish.password="${AEM_PASSWORD}" \
            -Dmaven.javadoc.skip=true \
            -Dmaven.surefire.debug

  Product-tests:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - run:
          name: "download Eaas cli"
          command: |
            curl -L https://github.com/andresbott/aem-guides-wknd/releases/download/poc-eaas/eaas-0.4.4  --output eaas
            chmod +x ./eaas
            sudo mv ./eaas /usr/local/bin/eaas

      - run:
          name: "Eaas login"
          command: |
            echo "${SERVICE_ACCOUNT_PRIVATE_KEY_B64}" | base64 -d > private.key
            eaas --url="https://devxapi.adobe.io" login integration  \
              --organization "${SERVICE_ACCOUNT_ORG_ID}" \
              --clientId "${SERVICE_ACCOUNT_CLIENT_ID}" \
              --secret "${SERVICE_ACCOUNT_CLIENT_SECRET}" \
              --privateKey private.key \
              --accountId "${SERVICE_ACCOUNT_TECH_ACCOUNT_ID}"            
            eaas health
      - run:
          name: "Generate the IT payload"
          command: |
            eaas generate it-task-payload
            
            sed -i "s|groupId:test-module-artifactId:version|com.adobe.cq.cloud:com.adobe.cq.cloud.testing.it.smoke:0.14.8-4f7653d|g ;
            s|https:\/\/author-skyline:port|${AUTHOR_URL}|g ;
            s|https:\/\/publish-skyline:port|${PUBLISH_URL}|g ;
            s/authorPV\\$\\$/${AEM_PASSWORD}/g ;
            s/publishPV\\$\\$/${AEM_PASSWORD}/g ;
            s/user\":\ \"admin/user\": \"${AEM_USER}/g ;
            " it-task-payload.json            

      - run:
          name: "Run the IT task"
          command: |
            # Start the IT Task            
            eaas start it-task -f it-task-payload.json | tee it-task.out
            task_id="`cat it-task.out | grep "Id:" | awk -F':' '{print $2}' | xargs`"
            if [[ "${task_id}" == "" ]]; then
                echo "EAAS failed to generate task_id"
                exit 1
            fi
            
            # Check IT Task status
            start_time="`date +%s`"
            IT_TASK_TIMEOUT=900
            status_file="taskId-${task_id}.status"
            while true; do
              eaas status it-task --taskId ${task_id} | tee "${status_file}"
              test_status="`cat "${status_file}" | grep "Status:" | awk -F':' '{print $2}' | xargs `"
              if [[ "${test_status}" == "terminated" || "${test_status}" == "failed" || $((`date +%s` - ${start_time})) -gt ${IT_TASK_TIMEOUT} ]]; then
                break
              fi
            echo "waiting 10s to check again for task status"
            sleep 10
            done
            
            # parse results
            test_passed="`cat "${status_file}" | grep "Tests passed:" | awk -F':' '{print $2}' | xargs `"
            echo ${task_id}
            echo ${test_status} 
            echo ${test_passed} 
            
            # Generate task exit code
            if [[ "${test_passed}" == "true" ]]; then exit 0; else exit 1; fi           
      

  Cleanup:
    docker:
      - image: cimg/openjdk:11.0-node
    steps:
      - checkout
      - run:
          name: Uninstall the user from the RDE
          command: |
            # Note: repoinit has some limitations with special characters in password, e.g. "+" sign
            .circleci/create-user-osgi-cfg.sh -u "${AEM_USER}" -p "${AEM_PASSWORD}" -q true
            
            aio aem:rde:install -t osgi-config org.apache.sling.jcr.repoinit.RepositoryInitializer~testadmin-user-remove.cfg.json
            aio aem:rde:delete org.apache.sling.jcr.repoinit.RepositoryInitializer~testadmin-user-remove
          when: always

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  PR-validation:
    jobs:
      - Build
#      - RDE-reset
      - RDE-install:
          requires:
            - Build
#            - RDE-reset

      - Customer-ITs:
          requires:
            - RDE-install
      - Product-tests:
          requires:
            - RDE-install
      - Cleanup:
          requires:
            - Product-tests
            - Customer-ITs