name: RDE verify
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out Git repository
      - uses: actions/checkout@v3

      # Set up environment with Java and Maven
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: maven

#      # Set up dependency cache
#      - name: Cache local Maven repository
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            maven-${{ hashFiles('**/pom.xml') }}

      # Build & Test
      - name: Build & Test with Maven
        run: mvn clean install

      - name: persist generated artifacts
        uses: actions/upload-artifact@v3
        with:
          name: maven files
          path: |
            all/target/*.zip
            dispatcher/target/*.zip